apiVersion: apps/v1
kind: Deployment
metadata:
  name: patient
spec:
  replicas: 1
  selector:
    matchLabels:
      app: patient
  template:
    metadata:
      labels:
        app: patient
    spec:
      containers:
      - name: patient
        image: hakan.tutar/patient:latest
        ports:
        - containerPort: 5005