apiVersion: apps/v1
kind: Deployment
metadata:
  name: question
spec:
  replicas: 1
  selector:
    matchLabels:
      app: question
  template:
    metadata:
      labels:
        app: question
    spec:
      containers:
      - name: question
        image: hakan.tutar/question:latest
        ports:
        - containerPort: 5003